//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lightoxs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhan
    {
        public int TinNhan_ID { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
    }
}
